# Generated by Django 4.1.7 on 2023-03-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_rename_food_orderitem_fooditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddress',
            new_name='DeliveryAddress',
        ),
    ]
