# Generated by Django 4.1.7 on 2023-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_rename_customeraddress_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
